fix: small typos and little improvements to the text
carrot-kpi/docs pull request #3
Opened 2023-04-13 23:01 UTC by Diogomartf

2023-04-14 08:47 UTC, guerrap commented on pages/protocol/introduction.mdx
>  -   **Condition**: the goal needs to be turned to a condition so that Carrot can
I think it should be `turned into a condition`.

2023-04-14 08:52 UTC, guerrap commented on pages/protocol/introduction.mdx
> +    the collateral, in this case, the goal is partially or fully reached.
Why this change? It was correct.

2023-04-14 09:00 UTC, guerrap requested changes

2023-04-14 09:00 UTC, guerrap commented on pages/protocol/kpi-tokens.mdx
> +They represent on-chain the condition that the user wants to incentivize, the
I'd add `and` after  `wants to incentivize, and the ...`.

2023-04-14 11:05 UTC, Diogomartf commented on pages/protocol/introduction.mdx
> +    the collateral, in this case, the goal is partially or fully reached.
It did feel it needed a pause, that's why I putted under ",".

I like your version.

There is one things that doesn't sound good to me: `in case the goal`, shouldn't it be, `in this case the goal` ?

2023-04-14 11:06 UTC, Diogomartf commented on pages/protocol/introduction.mdx
>  -   **Condition**: the goal needs to be turned to a condition so that Carrot can
yes. tks

2023-04-14 12:16 UTC, Diogomartf commented on pages/protocol/kpi-tokens.mdx
> +They represent on-chain the condition that the user wants to incentivize, the
fixed.

2023-04-17 12:21 UTC, guerrap commented on pages/protocol/introduction.mdx
> +    the collateral, in this case, the goal is partially or fully reached.
We can rewrite it this way:
```
KPI tokens essentially represent a claim to all or part of the collateral whenever the goal is either fully reached or partially reached.
```

2023-04-17 13:18 UTC, Diogomartf commented on pages/protocol/introduction.mdx
> +    the collateral, in this case, the goal is partially or fully reached.
fixed [6148242](https://github.com/carrot-kpi/docs/pull/3/commits/6148242a14921c7f060657965209efa4a9df0935)

2023-04-17 13:18 UTC, Diogomartf commented on pages/protocol/introduction.mdx
> +    the collateral, in this case, the goal is partially or fully reached.
fixed [6148242](https://github.com/carrot-kpi/docs/pull/3/commits/6148242a14921c7f060657965209efa4a9df0935)

2023-04-17 13:30 UTC, guerrap commented on pages/protocol/introduction.mdx
> --   **KPI tokens**: KPI tokens essentially represent a claim to all or part of
Remove the `We can rewrite it this way:` part.

2023-04-17 13:31 UTC, guerrap requested changes

2023-04-17 13:31 UTC, guerrap commented on pages/protocol/introduction.mdx
> +-   **KPI tokens**: We can rewrite it this way: KPI tokens essentially represent
Remove the `We can rewrite it this way: part.` part.

2023-04-20 15:35 UTC, Diogomartf commented on pages/protocol/introduction.mdx
> +-   **KPI tokens**: We can rewrite it this way: KPI tokens essentially represent
sorry!! my bad

2023-04-20 15:36 UTC, Diogomartf commented on pages/protocol/introduction.mdx
> +-   **KPI tokens**: We can rewrite it this way: KPI tokens essentially represent
fixed [e72a6a4](https://github.com/carrot-kpi/docs/pull/3/commits/e72a6a4fb3eeb97800543aaa650dbb5003d6d003)

2023-04-20 15:38 UTC, guerrap approved these changes

2023-04-24 20:26 UTC, luzzif approved these changes

2023-04-24 20:27 UTC, merged